package it.polimi.ingsw.gc49;

public enum BuildingEvent {
    HUNTING_EVENT,
    PAINTING_EVENT,
    RITUAL_PRIOR_EVENT,
    RITUAL_POSTERIOR_EVENT,
    SUSTENANCE_EVENT,
    SETCOMPLETE_EVENT,
    SAMEINVENTION_EVENT,
    TURN_END,
    ROUND_END,
    GAMA_END,
}